const menu = [
  {
    id: 1,
    title: "buttermilk pancakes",
    category: "breakfast",
    price: 15.99,
    img: "https://sugarspunrun.com/wp-content/uploads/2019/03/Best-buttermilk-pancake-recipe-11-of-16.jpg",
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 2,
    title: "diner double",
    category: "lunch",
    price: 13.99,
    img: "https://www.abcpizzashop.com/assets/images/dinner_double_cheeseburger.jpg",
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 3,
    title: "godzilla milkshake",
    category: "shakes",
    price: 6.99,
    img: "https://i2-prod.glasgowlive.co.uk/incoming/article16335485.ece/ALTERNATES/s615b/0_DSC_5315.jpg",
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
  },
  {
    id: 4,
    title: "country delight",
    category: "breakfast",
    price: 20.99,
    img: "https://www.thespruceeats.com/thmb/KgvlR1hd_YETqFFqQm7P2HycqJE=/2667x2000/smart/filters:no_upscale()/country-breakfast-skillet-recipe-3056473-Hero_01-c1af3dae64054fc480c668f205d9514c.jpg",
    desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
  },
  {
    id: 5,
    title: "egg attack",
    category: "lunch",
    price: 22.99,
    img: "https://images-gmi-pmc.edge-generalmills.com/ea9acd6c-3d2b-49a3-8a1d-39671f008e7f.jpg",
    desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
  },
  {
    id: 6,
    title: "oreo dream",
    category: "shakes",
    price: 18.99,
    img: "https://thesaltymarshmallow.com/wp-content/uploads/2018/08/oreo-milkshakes1.jpg",
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 7,
    title: "bacon overflow",
    category: "breakfast",
    price: 8.99,
    img: "https://whenisdinner.com/wp-content/uploads/2019/06/Chicken-Bacon-Ranch-Poppers-Horiz.jpg",
    desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
  },
  {
    id: 8,
    title: "american classic",
    category: "lunch",
    price: 12.99,
    img: "https://img-global.cpcdn.com/recipes/9ca90ea94afd5c1f/1200x630cq70/photo.jpg",
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
  },
  {
    id: 9,
    title: "quarantine buddy",
    category: "shakes",
    price: 16.99,
    img: "https://www.howtocookthat.net/public_html/wp-content/uploads/2016/06/freakshakes-2-550x309.jpg",
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 10,
    title: "quarantine buddy",
    category: "dinner",
    price: 1.0,
    img: "https://cdn2.momjunction.com/wp-content/uploads/2017/06/How-To-Be-A-Good-Father-Qualities-And-Involvement.jpg",
    desc: "A whole bunch of families are together during the pandemic because everything was closed.",
  },
];
export default menu;
